# Generated by Django 5.2.1 on 2025-06-16 14:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host_nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('enable_dummy', models.BooleanField(default=False)),
                ('role_groups', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_started', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=128)),
                ('roles', models.JSONField(default=list)),
                ('role_messages', models.JSONField(default=list)),
                ('role_images', models.JSONField(default=list)),
                ('faction', models.CharField(blank=True, default='unknown', max_length=50)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.gamesession')),
            ],
            options={
                'unique_together': {('game_session', 'nickname')},
            },
        ),
    ]
