# Generated by Django 5.2.1 on 2025-06-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='enable_dummy',
            field=models.BooleanField(default=False),
        ),
    ]
