# Generated by Django 5.2.1 on 2025-06-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_add_enable_dummy'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='faction',
            field=models.CharField(blank=True, default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='role_images',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='player',
            name='role_messages',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='player',
            name='roles',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='player',
            name='role_detail',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='role_image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='role_intro',
            field=models.TextField(blank=True, default=''),
        ),
    ]
