# Generated by Django 5.2.1 on 2025-06-16 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_faction_player_role_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='role',
        ),
        migrations.RemoveField(
            model_name='player',
            name='role_detail',
        ),
        migrations.RemoveField(
            model_name='player',
            name='role_image',
        ),
        migrations.RemoveField(
            model_name='player',
            name='role_intro',
        ),
    ]
